### ISSUE TITLE
It would be so awesome to support relative paths in .mg-config.json path

### ISSUE THREAD

**Issue by scottmas** [nicolas-schmitt/multi-git#5]
I really do like this library. Simple, which is what I need. Thank you for publishing it!

However, I want to create a repo that manages all my other repos. And thus I want to check in a .mg-config.json file. However, I know nothing about the host environment which the repo will be cloned to. Therefore I need relative urls.

It seems like this should be relatively easy but I looked in the source code and nothing obvious stuck out to me as being a place I could tweak this.

The rule could be as simple as "If the path starts with a `.` treat the path as relative"

**Comment by nicolas-schmitt** [comment]
Hi, thank you very much for the feedback 😸 
Since you already submited a PR, let's keep the conversation over there :)

**Comment by nicolas-schmitt** [comment]
Hi again, i just published a new version (2.3.0) supporting your request.
Paths can now be relative, prefixed or not with a dot.

Let me know if it fits your need or require some adjusting :smiley_cat:
